# .github/workflows/blank.yml
name: Caller Workflow (Pipeline 1)

on:
  push:
    branches:
      - main

jobs:
  call-pipeline2:
    uses: ezydevops473/pipeline2/.github/workflows/pipeline2.yml@main
    with:
      username: "ezydevops473"
    secrets:
      token: ${{ secrets.MY_SECRET_TOKEN }}
